# Generated by Django 3.1.2 on 2020-10-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20201028_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Projeye Fotoğraf Ekle'),
        ),
    ]
