# Generated by Django 3.1.2 on 2020-10-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='domment_date',
            new_name='comment_date',
        ),
    ]
