# Generated by Django 3.1.2 on 2020-10-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20201029_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_date']},
        ),
    ]
